#coupons
BsCheckout::Coupon.create!(code: 'qwerty123', value: '51,1')

#deliveries
BsCheckout::Delivery.create!(name: 'Delivery Next Day!', interval: '3 to 7 days', price: '28,50')
BsCheckout::Delivery.create!(name: 'Free!', interval: '10 days', price: '0')

#countries
BsCheckout::Country.create!(name: 'Afghanistan')
BsCheckout::Country.create!(name: 'Albania')
BsCheckout::Country.create!(name: 'Algeria')
BsCheckout::Country.create!(name: 'American Samoa')
BsCheckout::Country.create!(name: 'Andorra')
BsCheckout::Country.create!(name: 'Angola')
BsCheckout::Country.create!(name: 'Anguilla')
BsCheckout::Country.create!(name: 'Antarctica')
BsCheckout::Country.create!(name: 'Antigua and Barbuda')
BsCheckout::Country.create!(name: 'Argentina')
BsCheckout::Country.create!(name: 'Armenia')
BsCheckout::Country.create!(name: 'Aruba')
BsCheckout::Country.create!(name: 'Australia')
BsCheckout::Country.create!(name: 'Austria')
BsCheckout::Country.create!(name: 'Azerbaijan')
BsCheckout::Country.create!(name: 'Bahamas')
BsCheckout::Country.create!(name: 'Bahrain')
BsCheckout::Country.create!(name: 'Bangladesh')
BsCheckout::Country.create!(name: 'Barbados')
BsCheckout::Country.create!(name: 'Belarus')
BsCheckout::Country.create!(name: 'Belgium')
BsCheckout::Country.create!(name: 'Belize')
BsCheckout::Country.create!(name: 'Benin')
BsCheckout::Country.create!(name: 'Bermuda')
BsCheckout::Country.create!(name: 'Bhutan')
BsCheckout::Country.create!(name: 'Bolivia')
BsCheckout::Country.create!(name: 'Bosnia and Herzegovina')
BsCheckout::Country.create!(name: 'Botswana')
BsCheckout::Country.create!(name: 'Bouvet Island')
BsCheckout::Country.create!(name: 'Brazil')
BsCheckout::Country.create!(name: 'British Indian Ocean Territory')
BsCheckout::Country.create!(name: 'Brunei Darussalam')
BsCheckout::Country.create!(name: 'Bulgaria')
BsCheckout::Country.create!(name: 'Burkina Faso')
BsCheckout::Country.create!(name: 'Burundi')
BsCheckout::Country.create!(name: 'Cambodia')
BsCheckout::Country.create!(name: 'Cameroon')
BsCheckout::Country.create!(name: 'Canada')
BsCheckout::Country.create!(name: 'Cape Verde')
BsCheckout::Country.create!(name: 'Cayman Islands')
BsCheckout::Country.create!(name: 'Central African Republic')
BsCheckout::Country.create!(name: 'Chad')
BsCheckout::Country.create!(name: 'Chile')
BsCheckout::Country.create!(name: 'China')
BsCheckout::Country.create!(name: 'Christmas Island')
BsCheckout::Country.create!(name: 'Cocos (Keeling) Islands')
BsCheckout::Country.create!(name: 'Colombia')
BsCheckout::Country.create!(name: 'Comoros')
BsCheckout::Country.create!(name: 'Congo')
BsCheckout::Country.create!(name: 'Cook Islands')
BsCheckout::Country.create!(name: 'Costa Rica')
BsCheckout::Country.create!(name: 'Croatia (Hrvatska)')
BsCheckout::Country.create!(name: 'Cuba')
BsCheckout::Country.create!(name: 'Cyprus')
BsCheckout::Country.create!(name: 'Czech Republic')
BsCheckout::Country.create!(name: 'Denmark')
BsCheckout::Country.create!(name: 'Djibouti')
BsCheckout::Country.create!(name: 'Dominica')
BsCheckout::Country.create!(name: 'Dominican Republic')
BsCheckout::Country.create!(name: 'East Timor')
BsCheckout::Country.create!(name: 'Ecuador')
BsCheckout::Country.create!(name: 'Egypt')
BsCheckout::Country.create!(name: 'El Salvador')
BsCheckout::Country.create!(name: 'Equatorial Guinea')
BsCheckout::Country.create!(name: 'Eritrea')
BsCheckout::Country.create!(name: 'Estonia')
BsCheckout::Country.create!(name: 'Ethiopia')
BsCheckout::Country.create!(name: 'Falkland Islands (Malvinas)')
BsCheckout::Country.create!(name: 'Faroe Islands')
BsCheckout::Country.create!(name: 'Fiji')
BsCheckout::Country.create!(name: 'Finland')
BsCheckout::Country.create!(name: 'France')
BsCheckout::Country.create!(name: 'France, Metropolitan')
BsCheckout::Country.create!(name: 'French Guiana')
BsCheckout::Country.create!(name: 'French Polynesia')
BsCheckout::Country.create!(name: 'French Southern Territories')
BsCheckout::Country.create!(name: 'Gabon')
BsCheckout::Country.create!(name: 'Gambia')
BsCheckout::Country.create!(name: 'Georgia')
BsCheckout::Country.create!(name: 'Germany')
BsCheckout::Country.create!(name: 'Ghana')
BsCheckout::Country.create!(name: 'Gibraltar')
BsCheckout::Country.create!(name: 'Guernsey')
BsCheckout::Country.create!(name: 'Greece')
BsCheckout::Country.create!(name: 'Greenland')
BsCheckout::Country.create!(name: 'Grenada')
BsCheckout::Country.create!(name: 'Guadeloupe')
BsCheckout::Country.create!(name: 'Guam')
BsCheckout::Country.create!(name: 'Guatemala')
BsCheckout::Country.create!(name: 'Guinea')
BsCheckout::Country.create!(name: 'Guinea-Bissau')
BsCheckout::Country.create!(name: 'Guyana')
BsCheckout::Country.create!(name: 'Haiti')
BsCheckout::Country.create!(name: 'Heard and Mc Donald Islands')
BsCheckout::Country.create!(name: 'Honduras')
BsCheckout::Country.create!(name: 'Hong Kong')
BsCheckout::Country.create!(name: 'Hungary')
BsCheckout::Country.create!(name: 'Iceland')
BsCheckout::Country.create!(name: 'India')
BsCheckout::Country.create!(name: 'Isle of Man')
BsCheckout::Country.create!(name: 'Indonesia')
BsCheckout::Country.create!(name: 'Iran (Islamic Republic of)')
BsCheckout::Country.create!(name: 'Iraq')
BsCheckout::Country.create!(name: 'Ireland')
BsCheckout::Country.create!(name: 'Israel')
BsCheckout::Country.create!(name: 'Italy')
BsCheckout::Country.create!(name: 'Ivory Coast')
BsCheckout::Country.create!(name: 'Jersey')
BsCheckout::Country.create!(name: 'Jamaica')
BsCheckout::Country.create!(name: 'Japan')
BsCheckout::Country.create!(name: 'Jordan')
BsCheckout::Country.create!(name: 'Kazakhstan')
BsCheckout::Country.create!(name: 'Kenya')
BsCheckout::Country.create!(name: 'Kiribati')
BsCheckout::Country.create!(name: 'Korea, Democratic People\'\'s Republic of')
BsCheckout::Country.create!(name: 'Korea, Republic of')
BsCheckout::Country.create!(name: 'Kosovo')
BsCheckout::Country.create!(name: 'Kuwait')
BsCheckout::Country.create!(name: 'Kyrgyzstan')
BsCheckout::Country.create!(name: 'Lao People''s Democratic Republic')
BsCheckout::Country.create!(name: 'Latvia')
BsCheckout::Country.create!(name: 'Lebanon')
BsCheckout::Country.create!(name: 'Lesotho')
BsCheckout::Country.create!(name: 'Liberia')
BsCheckout::Country.create!(name: 'Libyan Arab Jamahiriya')
BsCheckout::Country.create!(name: 'Liechtenstein')
BsCheckout::Country.create!(name: 'Lithuania')
BsCheckout::Country.create!(name: 'Luxembourg')
BsCheckout::Country.create!(name: 'Macau')
BsCheckout::Country.create!(name: 'Macedonia')
BsCheckout::Country.create!(name: 'Madagascar')
BsCheckout::Country.create!(name: 'Malawi')
BsCheckout::Country.create!(name: 'Malaysia')
BsCheckout::Country.create!(name: 'Maldives')
BsCheckout::Country.create!(name: 'Mali')
BsCheckout::Country.create!(name: 'Malta')
BsCheckout::Country.create!(name: 'Marshall Islands')
BsCheckout::Country.create!(name: 'Martinique')
BsCheckout::Country.create!(name: 'Mauritania')
BsCheckout::Country.create!(name: 'Mauritius')
BsCheckout::Country.create!(name: 'Mayotte')
BsCheckout::Country.create!(name: 'Mexico')
BsCheckout::Country.create!(name: 'Micronesia, Federated States of')
BsCheckout::Country.create!(name: 'Moldova, Republic of')
BsCheckout::Country.create!(name: 'Monaco')
BsCheckout::Country.create!(name: 'Mongolia')
BsCheckout::Country.create!(name: 'Montenegro')
BsCheckout::Country.create!(name: 'Montserrat')
BsCheckout::Country.create!(name: 'Morocco')
BsCheckout::Country.create!(name: 'Mozambique')
BsCheckout::Country.create!(name: 'Myanmar')
BsCheckout::Country.create!(name: 'Namibia')
BsCheckout::Country.create!(name: 'Nauru')
BsCheckout::Country.create!(name: 'Nepal')
BsCheckout::Country.create!(name: 'Netherlands')
BsCheckout::Country.create!(name: 'Netherlands Antilles')
BsCheckout::Country.create!(name: 'New Caledonia')
BsCheckout::Country.create!(name: 'New Zealand')
BsCheckout::Country.create!(name: 'Nicaragua')
BsCheckout::Country.create!(name: 'Niger')
BsCheckout::Country.create!(name: 'Nigeria')
BsCheckout::Country.create!(name: 'Niue')
BsCheckout::Country.create!(name: 'Norfolk Island')
BsCheckout::Country.create!(name: 'Northern Mariana Islands')
BsCheckout::Country.create!(name: 'Norway')
BsCheckout::Country.create!(name: 'Oman')
BsCheckout::Country.create!(name: 'Pakistan')
BsCheckout::Country.create!(name: 'Palau')
BsCheckout::Country.create!(name: 'Palestine')
BsCheckout::Country.create!(name: 'Panama')
BsCheckout::Country.create!(name: 'Papua New Guinea')
BsCheckout::Country.create!(name: 'Paraguay')
BsCheckout::Country.create!(name: 'Peru')
BsCheckout::Country.create!(name: 'Philippines')
BsCheckout::Country.create!(name: 'Pitcairn')
BsCheckout::Country.create!(name: 'Poland')
BsCheckout::Country.create!(name: 'Portugal')
BsCheckout::Country.create!(name: 'Puerto Rico')
BsCheckout::Country.create!(name: 'Qatar')
BsCheckout::Country.create!(name: 'Reunion')
BsCheckout::Country.create!(name: 'Romania')
BsCheckout::Country.create!(name: 'Russian Federation')
BsCheckout::Country.create!(name: 'Rwanda')
BsCheckout::Country.create!(name: 'Saint Kitts and Nevis')
BsCheckout::Country.create!(name: 'Saint Lucia')
BsCheckout::Country.create!(name: 'Saint Vincent and the Grenadines')
BsCheckout::Country.create!(name: 'Samoa')
BsCheckout::Country.create!(name: 'San Marino')
BsCheckout::Country.create!(name: 'Sao Tome and Principe')
BsCheckout::Country.create!(name: 'Saudi Arabia')
BsCheckout::Country.create!(name: 'Senegal')
BsCheckout::Country.create!(name: 'Serbia')
BsCheckout::Country.create!(name: 'Seychelles')
BsCheckout::Country.create!(name: 'Sierra Leone')
BsCheckout::Country.create!(name: 'Singapore')
BsCheckout::Country.create!(name: 'Slovakia')
BsCheckout::Country.create!(name: 'Slovenia')
BsCheckout::Country.create!(name: 'Solomon Islands')
BsCheckout::Country.create!(name: 'Somalia')
BsCheckout::Country.create!(name: 'South Africa')
BsCheckout::Country.create!(name: 'South Georgia South Sandwich Islands')
BsCheckout::Country.create!(name: 'Spain')
BsCheckout::Country.create!(name: 'Sri Lanka')
BsCheckout::Country.create!(name: 'St. Helena')
BsCheckout::Country.create!(name: 'St. Pierre and Miquelon')
BsCheckout::Country.create!(name: 'Sudan')
BsCheckout::Country.create!(name: 'Suriname')
BsCheckout::Country.create!(name: 'Svalbard and Jan Mayen Islands')
BsCheckout::Country.create!(name: 'Swaziland')
BsCheckout::Country.create!(name: 'Sweden')
BsCheckout::Country.create!(name: 'Switzerland')
BsCheckout::Country.create!(name: 'Syrian Arab Republic')
BsCheckout::Country.create!(name: 'Taiwan')
BsCheckout::Country.create!(name: 'Tajikistan')
BsCheckout::Country.create!(name: 'Tanzania, United Republic of')
BsCheckout::Country.create!(name: 'Thailand')
BsCheckout::Country.create!(name: 'Togo')
BsCheckout::Country.create!(name: 'Tokelau')
BsCheckout::Country.create!(name: 'Tonga')
BsCheckout::Country.create!(name: 'Trinidad and Tobago')
BsCheckout::Country.create!(name: 'Tunisia')
BsCheckout::Country.create!(name: 'Turkey')
BsCheckout::Country.create!(name: 'Turkmenistan')
BsCheckout::Country.create!(name: 'Turks and Caicos Islands')
BsCheckout::Country.create!(name: 'Tuvalu')
BsCheckout::Country.create!(name: 'Uganda')
BsCheckout::Country.create!(name: 'Ukraine')
BsCheckout::Country.create!(name: 'United Arab Emirates')
BsCheckout::Country.create!(name: 'United Kingdom')
BsCheckout::Country.create!(name: 'United States')
BsCheckout::Country.create!(name: 'United States minor outlying islands')
BsCheckout::Country.create!(name: 'Uruguay')
BsCheckout::Country.create!(name: 'Uzbekistan')
BsCheckout::Country.create!(name: 'Vanuatu')
BsCheckout::Country.create!(name: 'Vatican City State')
BsCheckout::Country.create!(name: 'Venezuela')
BsCheckout::Country.create!(name: 'Vietnam')
BsCheckout::Country.create!(name: 'Virgin Islands (British)')
BsCheckout::Country.create!(name: 'Virgin Islands (U.S.)')
BsCheckout::Country.create!(name: 'Wallis and Futuna Islands')
BsCheckout::Country.create!(name: 'Western Sahara')
BsCheckout::Country.create!(name: 'Yemen')
BsCheckout::Country.create!(name: 'Zaire')
BsCheckout::Country.create!(name: 'Zambia')
BsCheckout::Country.create!(name: 'Zimbabwe')
